export const routes = {
    home: '/',
    login: '/',
    forgotPassword: '/forgotPassword',
    verifyOtp: '/verifyOtp',
    changePassword: '/changePassword',
    registration: '/registration',
    schedule: '/schedule',
    customers: '/customers',
    revenue: '/revenue',
    report: '/report',
    clubWallet: '/clubWallet',
    activityLogs: '/activityLog',
    basicInformation: '/settings/edit-menu/basic-information',
    pinLocation: '/settings/edit-menu/pin-location',
    facilities: '/settings/edit-menu/facilities',
    openingHours: '/settings/edit-menu/opening-hours',
    manageCourts: '/settings/manage-courts',
    packages: '/settings/packages',
    holidays: '/settings/holidays',
    rolesAndPermissions: '/settings/roles-and-permissions',
    transactions: '/settings/manage-payment/transactions',
    paymentMethods: '/settings/manage-payment/payment-methods',
    discountCodes: '/settings/discount-codes',
};
